name: patroltracking
description: "An application to track the locations, details of the patrols."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  location: ^8.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  hive_flutter: ^1.1.0
  permission_handler: ^11.4.0
  mobile_scanner: ^6.0.7
  signature: ^5.5.0
  record: ^6.0.0
  flutter_sound: ^9.28.0
  path_provider: ^2.1.5
  http: ^1.3.0
  flutter_polyline_points: ^2.1.0
  video_player: ^2.9.5
  chewie: ^1.11.1
  audioplayers: ^6.4.0
  fluttertoast: ^8.2.12
  file_picker: ^10.1.2
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  camera: ^0.11.1
  nfc_manager: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/font/
    - assets/Patrols/


  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/font/RedHatDisplay-Black.ttf
          weight: 900
        - asset: assets/font/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/font/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: assets/font/RedHatDisplay-Regular.ttf
          weight: 400

